version: '3.2'
services:
  database:
    image: mysql:latest
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db-data:/var/lib/mysql/
    environment:
      - "MYSQL_DATABASE=sqldesigner"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "BIND-ADDRESS=0.0.0.0"
    ports:
      - "3306:3306"
  
  backend:
    build:
      context: ./src
      dockerfile: backend.dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /opt/src
      - ./src/logs:/opt/src/logs
    ports: 
      - "9000:9000"     
  
  web:
    build:
      context: ./web/
      dockerfile: frontend.dockerfile
    volumes:
      - type: bind
        source: ./web/
        target: /opt/web
    ports:
      - "3000:3000"
    depends_on:
      - backend
  nginx:
    build:
      context: ./deploy/docker/nginx
      dockerfile: nginx.dockerfile
    ports:
      - "8000:8000"
    depends_on:
        - backend
        - web
volumes:
  db-data:

      
